"""some changes in source

Revision ID: d4fbc7c85e12
Revises: 331f02b85d08
Create Date: 2026-06-18 23:03:51.649293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fbc7c85e12'
down_revision: Union[str, Sequence[str], None] = '331f02b85d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'total_pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
