"""...

Revision ID: eec1967d0a4f
Revises: f04ecd621545
Create Date: 2026-07-08 15:14:16.377346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec1967d0a4f'
down_revision: Union[str, Sequence[str], None] = 'f04ecd621545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_triggered_artifact_id'), table_name='chat_messages')
    op.drop_constraint(op.f('chat_messages_triggered_artifact_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'triggered_artifact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('triggered_artifact_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_messages_triggered_artifact_id_fkey'), 'chat_messages', 'artifacts', ['triggered_artifact_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_chat_messages_triggered_artifact_id'), 'chat_messages', ['triggered_artifact_id'], unique=False)
    # ### end Alembic commands ###
