"""add triggered_artifact_id to chat_messages

Revision ID: f04ecd621545
Revises: b583be26441b
Create Date: 2026-07-08 14:52:46.530081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04ecd621545'
down_revision: Union[str, Sequence[str], None] = 'b583be26441b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('triggered_artifact_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chat_messages_triggered_artifact_id'), 'chat_messages', ['triggered_artifact_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'artifacts', ['triggered_artifact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_triggered_artifact_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'triggered_artifact_id')
    # ### end Alembic commands ###
